const { POKENAME } = require('pokemon')
const { ATTRACTED_HELPER } = require('utils')

module.exports = {
  basic: [
    ATTRACTED_HELPER(POKENAME.GOLDEEN, 0.167),
    ATTRACTED_HELPER(POKENAME.KRABBY, 0.167),
    ATTRACTED_HELPER(POKENAME.POLIWAG, 0.167),
    ATTRACTED_HELPER(POKENAME.PSYDUC, 0.167),
    ATTRACTED_HELPER(POKENAME.STARYU, 0.167),
    ATTRACTED_HELPER(POKENAME.TENTACOOL, 0.167),
  ],
  good: [
    ATTRACTED_HELPER(POKENAME.HORSEA, 0.245),
    ATTRACTED_HELPER(POKENAME.SEEL, 0.245),
    ATTRACTED_HELPER(POKENAME.SHELLDER, 0.245),
    ATTRACTED_HELPER(POKENAME.SLOWPOKE, 0.245),
    ATTRACTED_HELPER(POKENAME.KABUTO, 0.012),
    ATTRACTED_HELPER(POKENAME.OMANYTE, 0.012),
  ],
  very_good: [
    ATTRACTED_HELPER(POKENAME.HORSEA, 0.146),
    ATTRACTED_HELPER(POKENAME.SEEL, 0.146),
    ATTRACTED_HELPER(POKENAME.SHELLDER, 0.146),
    ATTRACTED_HELPER(POKENAME.SLOWPOKE, 0.146),
    ATTRACTED_HELPER(POKENAME.MAGIKARP, 0.058),
    ATTRACTED_HELPER(POKENAME.SQUIRTLE, 0.058),
    ATTRACTED_HELPER(POKENAME.KABUTO, 0.135),
    ATTRACTED_HELPER(POKENAME.OMANYTE, 0.135),
    ATTRACTED_HELPER(POKENAME.LAPRAS, 0.037),
  ],
  special: [],
}
