const { POKENAME } = require('pokemon')
const { ATTRACTED_HELPER } = require('utils')

module.exports = {
  basic: [
    ATTRACTED_HELPER(POKENAME.GOLDEEN, 0.143),
    ATTRACTED_HELPER(POKENAME.GROWLITHE, 0.143),
    ATTRACTED_HELPER(POKENAME.KRABBY, 0.143),
    ATTRACTED_HELPER(POKENAME.MANKEY, 0.143),
    ATTRACTED_HELPER(POKENAME.SPEAROW, 0.143),
    ATTRACTED_HELPER(POKENAME.VOLTORB, 0.143),
    ATTRACTED_HELPER(POKENAME.VULPIX, 0.143),
  ],
  good: [
    ATTRACTED_HELPER(POKENAME.DIGLETT, 0.164),
    ATTRACTED_HELPER(POKENAME.DODUO, 0.164),
    ATTRACTED_HELPER(POKENAME.LICKITUNG, 0.164),
    ATTRACTED_HELPER(POKENAME.PARAS, 0.164),
    ATTRACTED_HELPER(POKENAME.PORYGON, 0.164),
    ATTRACTED_HELPER(POKENAME.SLOWPOKE, 0.164),
  ],
  very_good: [
    ATTRACTED_HELPER(POKENAME.DIGLETT, 0.13),
    ATTRACTED_HELPER(POKENAME.DODUO, 0.13),
    ATTRACTED_HELPER(POKENAME.LICKITUNG, 0.13),
    ATTRACTED_HELPER(POKENAME.PARAS, 0.13),
    ATTRACTED_HELPER(POKENAME.PORYGON, 0.13),
    ATTRACTED_HELPER(POKENAME.SLOWPOKE, 0.13),
    ATTRACTED_HELPER(POKENAME.CHARMANDER, 0.043),
    ATTRACTED_HELPER(POKENAME.EEVEE, 0.043),
    ATTRACTED_HELPER(POKENAME.FARFETCH_D, 0.043),
    ATTRACTED_HELPER(POKENAME.HITMONCHAN, 0.033),
    ATTRACTED_HELPER(POKENAME.KABUTO, 0.033),
  ],
  special: [
    ATTRACTED_HELPER(POKENAME.CHARMANDER, 0.198),
    ATTRACTED_HELPER(POKENAME.FARFETCH_D, 0.198),
    ATTRACTED_HELPER(POKENAME.EEVEE, 0.198),
    ATTRACTED_HELPER(POKENAME.HITMONCHAN, 0.15),
    ATTRACTED_HELPER(POKENAME.KABUTO, 0.15),
    ATTRACTED_HELPER(POKENAME.JYNX, 0.036),
    ATTRACTED_HELPER(POKENAME.MAGMAR, 0.036),
    ATTRACTED_HELPER(POKENAME.PINSIR, 0.036),
  ],
}
