const { POKENAME } = require('pokemon')
const { ATTRACTED_HELPER } = require('utils')

module.exports = {
  basic: [],
  good: [
    ATTRACTED_HELPER(POKENAME.EKANS, 0.245),
    ATTRACTED_HELPER(POKENAME.GRIMER, 0.245),
    ATTRACTED_HELPER(POKENAME.KOFFING, 0.245),
    ATTRACTED_HELPER(POKENAME.ZUBAT, 0.245),
  ],
  very_good: [
    ATTRACTED_HELPER(POKENAME.EKANS, 0.18),
    ATTRACTED_HELPER(POKENAME.GRIMER, 0.18),
    ATTRACTED_HELPER(POKENAME.KOFFING, 0.18),
    ATTRACTED_HELPER(POKENAME.ZUBAT, 0.18),
    ATTRACTED_HELPER(POKENAME.BULBASAUR, 0.144),
    ATTRACTED_HELPER(POKENAME.VENONAT, 0.09),
    ATTRACTED_HELPER(POKENAME.GASTLY, 0.045),
  ],
  special: [
    ATTRACTED_HELPER(POKENAME.BULBASAUR, 0.516),
    ATTRACTED_HELPER(POKENAME.VENONAT, 0.323),
    ATTRACTED_HELPER(POKENAME.GASTLY, 0.161),
  ],
}
