const { POKENAME } = require('pokemon')
const { ATTRACTED_HELPER } = require('utils')

module.exports = {
  basic: [
    ATTRACTED_HELPER(POKENAME.CATERPIE, 0.2),
    ATTRACTED_HELPER(POKENAME.NIDORAN_MALE, 0.2),
    ATTRACTED_HELPER(POKENAME.POLIWAG, 0.2),
    ATTRACTED_HELPER(POKENAME.RATTATA, 0.2),
    ATTRACTED_HELPER(POKENAME.TENTACOOL, 0.2),
  ],
  good: [
    ATTRACTED_HELPER(POKENAME.EKANS, 0.197),
    ATTRACTED_HELPER(POKENAME.GRIMER, 0.197),
    ATTRACTED_HELPER(POKENAME.HORSEA, 0.197),
    ATTRACTED_HELPER(POKENAME.KOFFING, 0.197),
    ATTRACTED_HELPER(POKENAME.MACHOP, 0.197),
  ],
  very_good: [
    ATTRACTED_HELPER(POKENAME.EKANS, 0.154),
    ATTRACTED_HELPER(POKENAME.GRIMER, 0.154),
    ATTRACTED_HELPER(POKENAME.HORSEA, 0.154),
    ATTRACTED_HELPER(POKENAME.KOFFING, 0.154),
    ATTRACTED_HELPER(POKENAME.MACHOP, 0.154),
    ATTRACTED_HELPER(POKENAME.MAGIKARP, 0.077),
    ATTRACTED_HELPER(POKENAME.SQUIRTLE, 0.077),
    ATTRACTED_HELPER(POKENAME.OMANYTE, 0.039),
  ],
  special: [
    ATTRACTED_HELPER(POKENAME.MAGIKARP, 0.336),
    ATTRACTED_HELPER(POKENAME.SQUIRTLE, 0.336),
    ATTRACTED_HELPER(POKENAME.OMANYTE, 0.168),
    ATTRACTED_HELPER(POKENAME.DITTO, 0.04),
    ATTRACTED_HELPER(POKENAME.DRATINI, 0.04),
    ATTRACTED_HELPER(POKENAME.LAPRAS, 0.04),
    ATTRACTED_HELPER(POKENAME.TANGELA, 0.04),
  ],
}
