const { POKENAME } = require('pokemon')
const { ATTRACTED_HELPER } = require('utils')

module.exports = {
  basic: [
    ATTRACTED_HELPER(POKENAME.GEODUDE, 0.25),
    ATTRACTED_HELPER(POKENAME.NIDORAN_FEMALE, 0.25),
    ATTRACTED_HELPER(POKENAME.ODDISH, 0.25),
    ATTRACTED_HELPER(POKENAME.RHYHORN, 0.25),
  ],
  good: [
    ATTRACTED_HELPER(POKENAME.CLEFAIRY, 0.124),
    ATTRACTED_HELPER(POKENAME.EXEGGCUTE, 0.124),
    ATTRACTED_HELPER(POKENAME.JIGGLYPUFF, 0.124),
    ATTRACTED_HELPER(POKENAME.MAGNEMITE, 0.124),
    ATTRACTED_HELPER(POKENAME.ONIX, 0.124),
    ATTRACTED_HELPER(POKENAME.SEEL, 0.124),
    ATTRACTED_HELPER(POKENAME.SHELLDER, 0.124),
    ATTRACTED_HELPER(POKENAME.ZUBAT, 0.124),
  ],
  very_good: [
    ATTRACTED_HELPER(POKENAME.CLEFAIRY, 0.103),
    ATTRACTED_HELPER(POKENAME.CUBONE, 0.103),
    ATTRACTED_HELPER(POKENAME.EXEGGCUTE, 0.103),
    ATTRACTED_HELPER(POKENAME.JIGGLYPUFF, 0.103),
    ATTRACTED_HELPER(POKENAME.MAGNEMITE, 0.103),
    ATTRACTED_HELPER(POKENAME.ONIX, 0.103),
    ATTRACTED_HELPER(POKENAME.SEEL, 0.103),
    ATTRACTED_HELPER(POKENAME.SHELLDER, 0.103),
    ATTRACTED_HELPER(POKENAME.ZUBAT, 0.103),
    ATTRACTED_HELPER(POKENAME.VENONAT, 0.051),
  ],
  special: [
    ATTRACTED_HELPER(POKENAME.CUBONE, 0.571),
    ATTRACTED_HELPER(POKENAME.VENONAT, 0.286),
    ATTRACTED_HELPER(POKENAME.AERODACTYL, 0.029),
    ATTRACTED_HELPER(POKENAME.CHANSEY, 0.029),
    ATTRACTED_HELPER(POKENAME.GASTLY, 0.029),
    ATTRACTED_HELPER(POKENAME.MR_MIME, 0.029),
    ATTRACTED_HELPER(POKENAME.TAUROS, 0.029),
  ],
}
