const { POKENAME } = require('pokemon')
const { ATTRACTED_HELPER } = require('utils')

module.exports = {
  basic: [
    ATTRACTED_HELPER(POKENAME.GROWLITHE, 0.5),
    ATTRACTED_HELPER(POKENAME.VULPIX, 0.5),
  ],
  good: [
    ATTRACTED_HELPER(POKENAME.PONYTA, 0.952),
    ATTRACTED_HELPER(POKENAME.CHARMANDER, 0.038),
  ],
  very_good: [
    ATTRACTED_HELPER(POKENAME.PONYTA, 0.5),
    ATTRACTED_HELPER(POKENAME.CHARMANDER, 0.4),
    ATTRACTED_HELPER(POKENAME.MAGMAR, 0.1),
  ],
  special: [
    ATTRACTED_HELPER(POKENAME.CHARMANDER, 0.8),
    ATTRACTED_HELPER(POKENAME.MAGMAR, 0.2),
  ],
}
