const { POKENAME } = require('pokemon')
const { ATTRACTED_HELPER } = require('utils')

module.exports = {
  basic: [],
  good: [
    ATTRACTED_HELPER(POKENAME.ARTICUNO, 0.333),
    ATTRACTED_HELPER(POKENAME.MOLTRES, 0.333),
    ATTRACTED_HELPER(POKENAME.ZAPDOS, 0.333),
  ],
  very_good: [],
  special: [
    ATTRACTED_HELPER(POKENAME.ARTICUNO, 0.159),
    ATTRACTED_HELPER(POKENAME.MOLTRES, 0.159),
    ATTRACTED_HELPER(POKENAME.ZAPDOS, 0.159),
    ATTRACTED_HELPER(POKENAME.MEWTWO, 0.476),
    ATTRACTED_HELPER(POKENAME.MEW, 0.048),
  ],
}
