const { POKENAME } = require('pokemon')
const { ATTRACTED_HELPER } = require('utils')

module.exports = {
  basic: [
    ATTRACTED_HELPER(POKENAME.GEODUDE, 0.5),
    ATTRACTED_HELPER(POKENAME.RHYHORN, 0.5),
  ],
  good: [
    ATTRACTED_HELPER(POKENAME.ONIX, 0.973),
    ATTRACTED_HELPER(POKENAME.KABUTO, 0.012),
    ATTRACTED_HELPER(POKENAME.OMANYTE, 0.012),
  ],
  very_good: [
    ATTRACTED_HELPER(POKENAME.ONIX, 0.645),
    ATTRACTED_HELPER(POKENAME.KABUTO, 0.161),
    ATTRACTED_HELPER(POKENAME.OMANYTE, 0.161),
    ATTRACTED_HELPER(POKENAME.AERODACTYL, 0.032),
  ],
  special: [
    ATTRACTED_HELPER(POKENAME.KABUTO, 0.455),
    ATTRACTED_HELPER(POKENAME.OMANYTE, 0.455),
    ATTRACTED_HELPER(POKENAME.AERODACTYL, 0.091),
  ],
}
